//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarrerasBDEntities : DbContext
    {
        public CarrerasBDEntities()
            : base("name=CarrerasBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caballos> Caballos { get; set; }
        public virtual DbSet<CarreraJugador> CarreraJugador { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Jugadores> Jugadores { get; set; }
    }
}
